[FEATURE] Desenvolvimento da tela Splash
Lifeados/MyGarden pull request #22
Opened 2024-10-07 01:33 UTC by alineamorimdev

Esta PR tem como objetivo desenvolver a tela de splash com a contagem regressiva de 3 segundos para seguir pra a tela de onboarding.

![image](https://github.com/user-attachments/assets/1bf41600-cf7f-4517-a00e-8d10bf621c85)

2024-10-07 12:23 UTC, Lifeados commented
@alineamorimdev  está com erro no terminal ao rodar o app. Verifique suas rotas:

<img width="1085" alt="image" src="https://github.com/user-attachments/assets/20f52ca1-23c5-43a3-9883-fa3fb0aef4c1">

2024-10-07 12:36 UTC, Lifeados requested changes

2024-10-07 12:36 UTC, Lifeados commented on lib/ui/modules/onboarding/onboarding_page.dart
Essa pasta onboarding, não faz parte dessa demanda, favor remover.

2024-10-07 12:36 UTC, Lifeados commented on lib/ui/modules/splash/splash_page.dart
> +      Navigator.of(context).pushReplacementNamed('/onboarding');
Essa rota já existe?

2024-10-07 12:36 UTC, Lifeados commented on lib/ui/modules/splash/splash_page.dart
> +      body: Image.asset('lib/ui/assets/images/splash.png'),
Ao rodar em um celular menor, o layout quebrou:

![image](https://github.com/user-attachments/assets/c4b8df74-0cf0-4cbb-9584-9232bbd788d7)

2024-10-07 12:36 UTC, Lifeados commented on pubspec.yaml
> +    - lib/ui/assets/images/splash.png
Favor configurar os assets para que todas as imagens automaticamente sejam adicionadas.

2024-10-08 00:23 UTC, alineamorimdev commented on lib/ui/modules/onboarding/onboarding_page.dart
Esta pasta onboarding tinha na main, eu renomei para splash. 
![image](https://github.com/user-attachments/assets/cef22a39-02d8-41db-9f5e-776a0edc5573)

2024-10-08 00:25 UTC, alineamorimdev commented on lib/ui/modules/splash/splash_page.dart
> +      Navigator.of(context).pushReplacementNamed('/onboarding');
Removi este codigo, pois ainda não criei a tela de onboarding para esta PR.

![image](https://github.com/user-attachments/assets/49d91ee8-01d1-4f15-ac0f-a9c2c3979f18)

2024-10-08 00:34 UTC, alineamorimdev commented on lib/ui/modules/splash/splash_page.dart
> +      body: Image.asset('lib/ui/assets/images/splash.png'),
![image](https://github.com/user-attachments/assets/384ec40f-9a4b-4644-9d50-5046b1f8d791)

2024-10-08 00:34 UTC, alineamorimdev commented on pubspec.yaml
> +    - lib/ui/assets/images/splash.png
![image](https://github.com/user-attachments/assets/8655bcb7-d20d-415c-b6e0-5632ec0a0e4d)

2024-10-08 21:04 UTC, Lifeados approved these changes

2024-10-08 22:23 UTC, merged